# Generated by Django 5.1.1 on 2025-01-23 19:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='name',
            field=models.CharField(max_length=150, validators=[django.core.validators.RegexValidator('^[a-zA-Z0-9]+(( [a-zA-Z0-9]+)*(: [a-zA-Z0-9]+)*(- [a-zA-Z0-9]+)*(\\\'[a-zA-Z0-9]+)*(, [a-zA-Z0-9]+)*(\\([a-zA-Z0-9]+\\))*(\\[[a-zA-Z0-9]+\\])*("[a-zA-Z0-9]+")*)*$', message='Invalid format')]),
        ),
    ]
