# Generated by Django 5.1.1 on 2025-03-16 14:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cart',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to='api.cart'),
        ),
        migrations.AlterField(
            model_name='user',
            name='wishlist',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to='api.wishlist'),
        ),
    ]
