# Generated by Django 5.1.1 on 2025-01-26 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_resource_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='estimated_delivery_units',
            field=models.CharField(choices=[('day', 'day'), ('minute', 'minute'), ('hour', 'hour'), ('week', 'week'), ('month', 'month')], max_length=7),
        ),
    ]
