# Generated by Django 5.1.1 on 2025-01-26 18:33

import datetime
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_resource_estimated_delivery_units'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.DecimalField(blank=True, decimal_places=1, default=0.0, max_digits=2, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)])),
                ('title', models.CharField(max_length=150, validators=[django.core.validators.RegexValidator('^[a-zA-Z0-9]+(( [a-zA-Z0-9]+)*(: [a-zA-Z0-9]+)*(- [a-zA-Z0-9]+)*(\\\'[a-zA-Z0-9]+)*(, [a-zA-Z0-9]+)*(\\([a-zA-Z0-9]+\\))*(\\[[a-zA-Z0-9]+\\])*("[a-zA-Z0-9]+")*)*$', message='Invalid format')])),
                ('review', models.TextField(blank=True, validators=[django.core.validators.RegexValidator('^[a-zA-Z0-9]+(( [a-zA-Z0-9]+)*(: [a-zA-Z0-9]+)*(- [a-zA-Z0-9]+)*(\\\'[a-zA-Z0-9]+)*(, [a-zA-Z0-9]+)*(\\([a-zA-Z0-9]+\\))*(\\[[a-zA-Z0-9]+\\])*("[a-zA-Z0-9]+")*)*$', message='Invalid format')])),
                ('upload_date', models.DateField(default=datetime.datetime.now)),
                ('image', models.ImageField(upload_to='review_images/')),
                ('video', models.FileField(upload_to='review_videos/')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='api.resource')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
