# Generated by Django 5.1.1 on 2025-03-23 12:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_address_city_alter_address_first_line_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=150, validators=[django.core.validators.RegexValidator('^[a-zA-Z ]+$', message='Only letters are allowed'), django.core.validators.RegexValidator('^\\S+( \\S+)*$', message='Only one space between words')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=150, validators=[django.core.validators.RegexValidator('^[a-zA-Z ]+$', message='Only letters are allowed'), django.core.validators.RegexValidator('^\\S+( \\S+)*$', message='Only one space between words')]),
        ),
    ]
