# Generated by Django 5.1.1 on 2025-01-19 13:13

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_address_postcode_alter_user_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='address',
        ),
        migrations.AddField(
            model_name='address',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='address', to='api.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator('^[a-zA-Z0-9 ]+$', message='No special characters allowed'), django.core.validators.RegexValidator('^\\S+( \\S+)*$', message='Only one space between words')]),
        ),
        migrations.AlterField(
            model_name='address',
            name='first_line',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator('^[a-zA-Z0-9 ]+$', message='No special characters allowed'), django.core.validators.RegexValidator('^\\S+( \\S+)*$', message='Only one space between words')]),
        ),
        migrations.AlterField(
            model_name='address',
            name='postcode',
            field=models.CharField(max_length=7, validators=[django.core.validators.RegexValidator('^[A-Za-z0-9]{5,7}$', message='Enter 5-7 character postcode without spaces')]),
        ),
        migrations.AlterField(
            model_name='address',
            name='second_line',
            field=models.CharField(blank=True, max_length=255, validators=[django.core.validators.RegexValidator('^[a-zA-Z0-9 ]+$', message='No special characters allowed'), django.core.validators.RegexValidator('^\\S+( \\S+)*$', message='Only one space between words')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='description',
            field=models.TextField(blank=True, validators=[django.core.validators.RegexValidator('^\\S+( \\S+)*$', message='Only one space between words')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=150, validators=[django.core.validators.RegexValidator('^[a-zA-Z ]+$', message='No special characters allowed'), django.core.validators.RegexValidator('^\\S+( \\S+)*$', message='Only one space between words')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=150, validators=[django.core.validators.RegexValidator('^[a-zA-Z ]+$', message='No special characters allowed'), django.core.validators.RegexValidator('^\\S+( \\S+)*$', message='Only one space between words')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator('^07(\\d{8,9})$', message='Must be 10 or 11 digit number starting with 07')]),
        ),
    ]
