# Generated by Django 5.1.1 on 2025-02-04 11:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_review_image_alter_review_review_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='upload_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='review',
            name='upload_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
