# Generated by Django 5.1.1 on 2025-03-26 14:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_searchhistoryitem_last_searched'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_date',
            field=models.DateField(blank=True, default=datetime.datetime(2025, 3, 26, 14, 4, 25, 820531, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
