# Generated by Django 5.1.1 on 2025-04-28 11:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_order_delivery_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator('^\\S+( \\S+)*$', message='Only one space between words')]),
        ),
        migrations.AlterField(
            model_name='address',
            name='first_line',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator('^\\S+( \\S+)*$', message='Only one space between words')]),
        ),
        migrations.AlterField(
            model_name='address',
            name='postcode',
            field=models.CharField(max_length=7, validators=[django.core.validators.RegexValidator('^\\S+( \\S+)*$', message='Only one space between words')]),
        ),
        migrations.AlterField(
            model_name='address',
            name='second_line',
            field=models.CharField(blank=True, max_length=255, validators=[django.core.validators.RegexValidator('^\\S+( \\S+)*$', message='Only one space between words')]),
        ),
    ]
