# Generated by Django 5.1.1 on 2025-02-04 19:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_resource_unique_alter_resource_upload_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='author',
            field=models.CharField(max_length=150, validators=[django.core.validators.RegexValidator('^[a-zA-Z0-9]+( [a-zA-Z0-9]+)*$', message='Invalid format')]),
        ),
    ]
