# Generated by Django 5.1.1 on 2025-02-04 20:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_cart_items_wishlist_items_alter_cart_total_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='items',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='items',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
