# Generated by Django 5.1.1 on 2025-02-04 20:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_cart_items_alter_wishlist_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='user',
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='user',
        ),
        migrations.AddField(
            model_name='user',
            name='cart',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user', to='api.cart'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='wishlist',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user', to='api.wishlist'),
            preserve_default=False,
        ),
    ]
