# Generated by Django 5.1.1 on 2025-02-05 14:36

import api.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_remove_cart_user_remove_wishlist_user_user_cart_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='wishlist',
            field=models.OneToOneField(default=api.models.create_wishlist, on_delete=django.db.models.deletion.CASCADE, related_name='user', to='api.wishlist'),
        ),
    ]
