# Generated by Django 5.1.1 on 2025-02-19 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_user_wishlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlistresource',
            name='wishlist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlist_resource', to='api.wishlist'),
        ),
    ]
