# Generated by Django 5.1.1 on 2025-02-19 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_wishlistresource_wishlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlistresource',
            name='number',
        ),
    ]
