# Generated by Django 5.1.1 on 2025-02-23 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_image',
            field=models.ImageField(blank=True, upload_to='delivery_images/'),
        ),
    ]
