# Generated by Django 5.1.1 on 2025-02-23 19:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_alter_order_delivery_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='resource',
        ),
        migrations.CreateModel(
            name='OrderResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_resource', to='api.order')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resource', to='api.resource')),
            ],
        ),
    ]
