# Generated by Django 5.1.1 on 2025-02-23 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_remove_order_resource_orderresource'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderresource',
            name='number',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
