# Generated by Django 5.1.1 on 2025-02-24 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_orderresource_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='delivery_option',
        ),
        migrations.AddField(
            model_name='resource',
            name='allow_collection',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='resource',
            name='allow_delivery',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='resource',
            name='allow_return',
            field=models.BooleanField(default=False),
        ),
    ]
