# Generated by Django 5.1.1 on 2025-02-24 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_remove_resource_delivery_option_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='last_edited',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
