# Generated by Django 5.1.1 on 2025-02-25 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_messages_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='last_edited',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
