# Generated by Django 5.1.1 on 2025-02-25 23:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_messages_last_edited'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartresource',
            name='resource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_resource', to='api.resource'),
        ),
        migrations.AlterField(
            model_name='wishlistresource',
            name='resource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlist_resource', to='api.resource'),
        ),
    ]
