# Generated by Django 5.1.1 on 2025-02-26 00:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_alter_cartresource_resource_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='last_edited',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
