# Generated by Django 5.1.1 on 2025-02-26 00:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_alter_resource_last_edited'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='last_edited',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 26, 0, 6, 22, 416427, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='resource',
            name='last_edited',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
