# Generated by Django 5.1.1 on 2025-02-26 00:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_alter_messages_last_edited_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='last_edited',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
