# Generated by Django 5.1.1 on 2025-03-06 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='for_return',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
