# Generated by Django 5.1.1 on 2025-03-06 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_resource_for_return'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Placed', 'Placed'), ('Processing', 'Processing'), ('Cancelled', 'Cancelled'), ('Refund Rejected', 'Refund Rejected'), ('Dispatched', 'Dispatched'), ('Complete', 'Complete'), ('Requested Return', 'Requested Return'), ('Being Returned', 'Being Returned'), ('Refunded', 'Refunded')], default='Placed', max_length=16),
        ),
    ]
