# Generated by Django 5.1.1 on 2025-03-06 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_alter_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='for_return',
        ),
        migrations.AddField(
            model_name='orderresource',
            name='for_return',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderresource',
            name='number_for_return',
            field=models.IntegerField(default=False),
            preserve_default=False,
        ),
    ]
