# Generated by Django 5.1.1 on 2025-03-06 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_remove_resource_for_return_orderresource_for_return_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderresource',
            name='for_return',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='orderresource',
            name='number_for_return',
            field=models.IntegerField(default=0),
        ),
    ]
