# Generated by Django 5.1.1 on 2025-03-06 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_alter_orderresource_for_return_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderresource',
            name='return_method',
            field=models.CharField(choices=[('Delivery', 'Delivery'), ('Collection', 'Collection')], default='Delivery', max_length=10),
        ),
    ]
