# Generated by Django 5.1.1 on 2025-03-06 21:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_orderresource_return_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderresource',
            name='return_reason',
            field=models.TextField(blank=True, validators=[django.core.validators.RegexValidator('^\\S+( \\S+)*$', message='Only one space between words')]),
        ),
    ]
