# Generated by Django 5.1.1 on 2025-03-06 21:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_orderresource_return_reason'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderresource',
            name='return_method',
        ),
        migrations.RemoveField(
            model_name='orderresource',
            name='return_reason',
        ),
        migrations.AddField(
            model_name='order',
            name='return_method',
            field=models.CharField(choices=[('Delivery', 'Delivery'), ('Collection', 'Collection')], default='Delivery', max_length=10),
        ),
        migrations.AddField(
            model_name='order',
            name='return_reason',
            field=models.TextField(blank=True, validators=[django.core.validators.RegexValidator('^\\S+( \\S+)*$', message='Only one space between words')]),
        ),
    ]
