# Generated by Django 5.1.1 on 2025-03-07 10:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_remove_orderresource_return_method_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exchange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Cancelled', 'Cancelled'), ('Accepted', 'Accepted')], default='Pending', max_length=10)),
                ('resource1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resource1', to='api.resource')),
                ('resource2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resource2', to='api.resource')),
                ('user1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exchange_user1', to=settings.AUTH_USER_MODEL)),
                ('user2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exchange_user2', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
