# Generated by Django 5.1.1 on 2025-03-07 10:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0041_exchange'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchange',
            name='resource1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resource1', to='api.resource'),
        ),
    ]
