# Generated by Django 5.1.1 on 2025-03-07 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0042_alter_exchange_resource1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exchange',
            name='status',
        ),
        migrations.AddField(
            model_name='exchange',
            name='status1',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Cancelled', 'Cancelled'), ('Accepted', 'Accepted')], default='Pending', max_length=10),
        ),
        migrations.AddField(
            model_name='exchange',
            name='status2',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Cancelled', 'Cancelled'), ('Accepted', 'Accepted')], default='Pending', max_length=10),
        ),
    ]
