# Generated by Django 5.1.1 on 2025-03-07 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0043_remove_exchange_status_exchange_status1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchange',
            name='status1',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Rejected', 'Rejected'), ('Accepted', 'Accepted')], default='Pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='exchange',
            name='status2',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Rejected', 'Rejected'), ('Accepted', 'Accepted')], default='Pending', max_length=10),
        ),
    ]
