# Generated by Django 5.1.1 on 2025-03-07 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0044_alter_exchange_status1_alter_exchange_status2'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchange',
            name='resource1_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='exchange',
            name='resource2_number',
            field=models.IntegerField(default=0),
        ),
    ]
