# Generated by Django 5.1.1 on 2025-03-07 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0045_exchange_resource1_number_exchange_resource2_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_exchange',
            field=models.BooleanField(default=False),
        ),
    ]
