# Generated by Django 5.1.1 on 2025-03-11 16:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0047_searchhistory_searchhistoryitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Placed', 'Placed'), ('Processing', 'Processing'), ('Cancelled', 'Cancelled'), ('Return Rejected', 'Return Rejected'), ('Dispatched', 'Dispatched'), ('Complete', 'Complete'), ('Requested Return', 'Requested Return'), ('Being Returned', 'Being Returned'), ('Refunded', 'Refunded')], default='Placed', max_length=16),
        ),
        migrations.AlterField(
            model_name='searchhistory',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='search_history', to=settings.AUTH_USER_MODEL),
        ),
    ]
