# Generated by Django 5.1.1 on 2025-03-14 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Placed', 'Placed'), ('Processing', 'Processing'), ('Cancelled', 'Cancelled'), ('Dispatched', 'Dispatched'), ('Complete', 'Complete'), ('Return Started', 'Return Started'), ('Return Received', 'Return Received'), ('Refunded', 'Refunded')], default='Placed', max_length=16),
        ),
    ]
