# Generated by Django 5.1.1 on 2025-03-24 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_user_first_name_alter_user_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchhistoryitem',
            name='last_searched',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
